include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_relative_imports: true
    prefer_final_fields: true
    prefer_typing_uninitialized_variables: true
    avoid_returning_null: true
    prefer_single_quotes: true
    unnecessary_brace_in_string_interps: true
    prefer_if_null_operators: true
    prefer_is_not_empty: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true